#!/usr/bin/env bash

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd "$parent_path"

src_release=target/wasm32-unknown-unknown/release/
src_debug=target/wasm32-unknown-unknown/debug/
dst=.

cargo build --lib && \
cargo build --lib --release && \
cp --verbose "$src_debug"/*.wasm "$dst"/hook_debug.wasm && \
cp --verbose "$src_release"/*.wasm "$dst"/hook.wasm
